### ISSUE TITLE
Show menus

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#1]
## Value proposition

**As a** user,
**I want to** to see all the menus of the restaurant,
**so that** i can choose dishes.

## Description

![Bildschirmfoto 2022-06-24 um 14 34 59](https://user-images.githubusercontent.com/78706133/175538143-e357643e-81f5-4331-ab0e-fa23f551feb5.png)

## Acceptance criteria

- [x] Menus are showed with pictures, names
- [x] Menus can scroll up and down

## Complexity

Small

## Tasks

- [x] Create new branch
- [x] Add base styles
- [x] Create a array of Menus for a Restaurant, element of this array has id, picture, name and price
- [x] Show all menus on the page, menus can scroll vertically
- [x] Component test
- [x] Add this component to storybook
