### ISSUE TITLE
Cart page

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#11]
## Value proposition

**As a** user,
**I want to** see a cart page,
**so that** I can find all wanted dishes in this page.

## Description

![Bildschirmfoto 2022-07-07 um 09 55 36](https://user-images.githubusercontent.com/78706133/177721956-93cb0e48-bc50-486e-ad59-feb8412731d9.png)

## Acceptance criteria

- [x] Every dish in this page should be showed with price, quantity.
- [x] Dish can be removed from the page.
- [x] Quantity of every dish can be increased or decreased.
- [x] Sum of price showed

## Complexity

Small 

## Tasks

- [x] Create branch
- [x] Add base styles
- [x] Create cart page
