### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#12]
## Value proposition

**As a** user,
**I want to** go back and forth, up and down in a page, or go to different pages,
**so that** I can finish and review my order easily.

## Description

<img width="238" alt="Bildschirmfoto 2022-07-15 um 09 07 24" src="https://user-images.githubusercontent.com/78706133/179170693-a3e0b014-74d0-4ee8-a68c-f4f4ebfbb24a.png">

## Acceptance criteria

- [x] Every page has a scroll-to-top  button, users can scroll up easily
- [x] Detail page and shopping cart page have go to previous buttons
- [x] There is a navigation in footer area, users can go to different pages
- [x] Navigation sticks to the bottom, when user scroll up and down

## Complexity

Small

## Tasks

- [x] Create new branch
- [x] Create Navigation, BackToPreviousPage, and ScrollTop components
- [x] Ajust layout of the previous component if necessary
- [x] Test those components
- [x] Add those components to storybook
