### ISSUE TITLE
Review area fold and unfold

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#16]
## Value proposition

**As a** user,
**I want to** fold or unfold the review page
**so that** if there are to much reviews, I don't need to scroll all the way back.

## Description

<img width="323" alt="Bildschirmfoto 2022-07-07 um 12 19 18" src="https://user-images.githubusercontent.com/78706133/177751988-484e12df-8afd-4062-a2bb-f677cab5bb0d.png">

<img width="323" alt="Bildschirmfoto 2022-07-07 um 12 19 26" src="https://user-images.githubusercontent.com/78706133/177752038-b24c3389-9796-4aa1-82fd-2b8bff08c5dc.png">

## Acceptance criteria

- [ ] Reviews is by default folded
- [ ] If clicked on arrow button, reviews will be unfolded.
- [ ] Click on arrow button again, reviews will be folded.

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Add arrow button
- [ ] Add component test
- [ ] Add it to story book
