### ISSUE TITLE
Store the data in Data bank

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#17]
## Value proposition

**As a** user,
**I want **  the data stored in the data bank.
**so that** I'll use the app in another device.

## Acceptance criteria

- [ ] Data for the app will be stored in data bank.
- [ ] App can be used from another device.

## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] Store the data in data bank.
- [ ] Test if everything still works well.
