### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#19]
## Value proposition

**As a** user,
**I want to** pay by online bank in the app, or call a waiter through the app to pay,
**so that** I can pay my bill quickly and easily.

## Description

![Bildschirmfoto 2022-07-16 um 19 12 36](https://user-images.githubusercontent.com/78706133/179365198-dbded0a6-4ecf-46b7-b0e4-d2efd1fdd703.png)

![Bildschirmfoto 2022-07-16 um 19 00 42](https://user-images.githubusercontent.com/78706133/179365201-e713d5b6-4252-4206-af04-d9bccfa2e512.png)

![Bildschirmfoto 2022-07-16 um 19 25 12](https://user-images.githubusercontent.com/78706133/179365602-11f98db8-077c-4ef1-af33-215edde26580.png)

## Acceptance criteria

- [x] There are to choices on the shopping cart page: pay by online banking, call waiter to pay
- [x] If the user clicks pay by online banking, payment page will be showed to let the user finish payment. 
- [x] If the user clicks call the waiter to pay,  a message will show up: "You want to pay the bill, please wait a minute, the waiter will come to you soon."

## Complexity

 Medium 

## Tasks

- [x] Create branch
- [x] Create payment buttons and corresponding pages
- [x] Add click event to the buttons
- [x] Realize payment through stripe
