### ISSUE TITLE
Category for menus

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#2]
## Value proposition

**As a** user,
**I want to** see the dishes in different categories,
**so that** I can find a dish in interested category easily.

## Description

![Bildschirmfoto 2022-06-27 um 14 08 38](https://user-images.githubusercontent.com/78706133/175937831-b4bbc875-4d08-4fb2-821a-0628c85d1edf.png)

## Acceptance criteria

- [x]  Categories will be displayed in a row
- [x]  If user clicks on category all, all dishes will be displayed
- [x]  If user clicks on a specific category, the corresponding dishes will be displayed

## Complexity

Small

## Tasks

- [x] Create branch
- [x] Create categories
- [x] Add click event to every categories, so that if a category is clicked, the corresponding dishes will be displayed
- [x] Component test
- [x] Add category to storybook
