### ISSUE TITLE
Add Header

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#22]
## Value proposition

**As a** user,
**I want to** see header of the app
**so that** I can have a better user view.

## Description

<img width="231" alt="Bildschirmfoto 2022-07-19 um 19 43 22" src="https://user-images.githubusercontent.com/78706133/179815268-6770e178-557a-4206-9db2-acc308fcd08d.png">

## Acceptance criteria

- [ ] Header sticks on the top

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Create Header component
- [ ] Component test
- [ ] Add Component to Stroybook
