### ISSUE TITLE
Optimize the detail page

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#23]
## Value proposition

**As a** user,
**I want to** see a more clear and understanding detail page,
**so that** find dishes I like more easily.

## Acceptance criteria

- [ ] Detail page is optimized
- [ ] Spiciness will be showed with pepper icons, not numbers.

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] Optimize the code
