### ISSUE TITLE
Add home page

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#25]
## Value proposition

**As a** user,
**I want to** see a home page,
**so that**I can get start to order.

## Description

![Bildschirmfoto 2022-07-21 um 20 56 01](https://user-images.githubusercontent.com/78706133/180294473-60650aab-49db-43ab-9552-5ddb73d88f90.png)

## Acceptance criteria

- [ ] Default page of the app is home page.
- [ ] From home page, users can make login or go directly to menus to order.

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Create new page
- [ ] Add function to buttons
- [ ] Add home page to router and navigation
