### ISSUE TITLE
Add login function

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#28]
## Value proposition

**As a** user,
**I want to** login the app,
**so that** I can review my history orders.

## Description

<img width="249" alt="Bildschirmfoto 2022-07-22 um 05 00 11" src="https://user-images.githubusercontent.com/78706133/180353426-36ac5526-f0e0-4ed4-af50-71179c689fd6.png">

## Acceptance criteria

- [ ] User can login
- [ ] User can view menus and order food with or without login
- [ ] After login user can check history orders
- [ ] If the user logout, history orders can be seen.

## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] Create login page
- [ ] Add onClick event to the login button on login page
- [ ] Add backend code to handle the login request
- [ ] Add username and password in mongodb
- [ ] Change the logic in orders page, so that if the user login history orders can be seen, if the user logout, no history orders can be seen.
