### ISSUE TITLE
Detail pages

### ISSUE THREAD

**Issue by Huimin66** [Huimin66/capstone-project#3]
## Value proposition

**As a** user,
**I want to** see detail pages for every dish,
**so that** i can choose which dish i would like to order.

## Acceptance criteria

- [ ] Every dish in the menu has its own detail page
- [ ] In detail page picture, ingredient, taste and review will be displayed
- [ ] 
## Complexity

Small | Medium | Large

## Tasks

- [ ] Create branch
- [ ] Render information of every dish to the page
- [ ] If there is too much information, the page can scroll vertically
- [ ] Component test
- [ ] Add Component to Stroybook
