### ISSUE TITLE
Detail pages

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#3]
## Value proposition

**As a** user,
**I want to** see detail pages for every dish,
**so that** i can choose which dish i would like to order.

## Description

![Bildschirmfoto 2022-06-27 um 14 08 47](https://user-images.githubusercontent.com/78706133/175937981-70bf1a32-d47c-40f9-852d-7d28334417ef.png)

## Acceptance criteria

- [x] Every dish in the menu has its own detail page
- [x] In detail page picture, ingredient, taste and review will be displayed

## Complexity

Small

## Tasks

- [x] Create branch
- [x] Render information of every dish to the page
- [x] If there is too much information, the page can scroll vertically
- [x] Component test
- [x] Add Component to Stroybook
