### ISSUE TITLE
Add sign up function

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#32]
## Value proposition

**As a** user,
**I want to** sign up,
**so that** I can create username and password by my self.

## Description

<img width="268" alt="Bildschirmfoto 2022-07-23 um 11 49 47" src="https://user-images.githubusercontent.com/78706133/180600210-07fca32d-3a5d-4b91-8f9f-91f65faa3c75.png">

## Acceptance criteria

- [ ] User can sign up
- [ ] User information is stored in data bank.

## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] Create sign up page, handle on sign up event
- [ ] Write back end code that handle request from front end
