### ISSUE TITLE
Category for menus

### ISSUE THREAD

**Issue by Huimin66** [Huimin66/capstone-project#4]
## Value proposition

**As a** user,
**I want to** see the dishes in different categories,
**so that** I can easily find a dish easily in my interested category.

## Description

![Bildschirmfoto 2022-06-23 um 17 01 10 (2)](https://user-images.githubusercontent.com/78706133/175330853-92cff257-614c-4980-8b16-d0a3c4e1aef1.png)

## Acceptance criteria

- [ ]  Categories will be displayed in a row
- [ ]  If user clicks on a all, all dishes will be displayed
- [ ]  If user clicks on a category, the corresponding dishes will be displayed

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] Create categories
- [ ] Add click event to every categories, so that if a category is clicked, the corresponding dishes will be displayed
- [ ] Component test
- [ ] Add category to storybook
