### ISSUE TITLE
Submit action in detail page

### ISSUE THREAD

**Issue by HuiminFrontend** [Huimin66/capstone-project#4]
## Value proposition

**As a** user,
**I want to** click on the submit button in detail page,
**so that** I can add dish to cart.

## Description

<img width="238" alt="Bildschirmfoto 2022-07-10 um 10 04 54" src="https://user-images.githubusercontent.com/78706133/178136584-7b3c701e-3132-47ab-904c-8293aa2f3ce5.png">

## Acceptance criteria

- [x] Price will be displayed on the left.
- [x] Submit button will be displayed on the right, if user clicks on submit button, dish with quantity will added to the cart.

## Complexity

Small

## Tasks

- [x] Create new branch
- [x] Add base styles
- [x] Create a button, and span for number
- [x] Component test
- [x] Add this component to storybook
