### ISSUE TITLE
Show all the menus in different categories

### ISSUE THREAD

**Issue by Huimin66** [Huimin66/capstone-project#5]
## Value proposition

**As a** user,
**I want to** to see all the menus of the restaurant,
**so that** i can choose something to eat.

## Description

![Bildschirmfoto 2022-06-23 um 16 46 32 (2)](https://user-images.githubusercontent.com/78706133/175327852-068f6bcf-e69b-4f54-94f7-e19f901bd703.png)

## Acceptance criteria

- [ ] Menus are showed with pictures, names
- [ ] Menus can scroll up and down

## Complexity

Small

## Tasks

- [ ] Create new branch
- [ ] Create a array of Menus for a Restaurant
- [ ] Every element of this array has id, picture, name and price
- [ ] Component test
- [ ] Add this component to storybook
