### ISSUE TITLE
Show all the menus in different categories

### ISSUE THREAD

**Issue by Huimin66** [Huimin66/capstone-project#6]
## Value proposition

**As a** user,
**I want to** to see all the menus of the restaurant,
**so that** i can choose something to eat.

## Description

![Bildschirmfoto 2022-06-24 um 11 30 30](https://user-images.githubusercontent.com/78706133/175509017-46d60f2a-70c3-45b5-8671-23f41dd67120.png)

## Acceptance criteria

- [ ] Menus are showed with pictures, names
- [ ] Menus can scroll up and down
- [ ] Every Menus has a checkbox, that can be checked or unchecked
- [ ] A submit button sticks on bottom of the page

## Complexity

Small

## Tasks

- [ ] Create new branch
- [ ] Create a array of Menus for a Restaurant
- [ ] Every element of this array has id, picture, name and price
- [ ] Menus are displayed in a form, every menu information can be submitted later.
- [ ] Component test
- [ ] Add this component to storybook
